platform :ios, '9.0'
use_frameworks!

target 'BRCJ' do

pod 'AFNetworking','~> 3.1.0'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15'
pod 'SDWebImage', '~> 5.0.0'
pod 'YYImage'
pod 'YYText'
pod 'SDCycleScrollView', '~> 1.80'
pod 'MJExtension', '~> 3.0.17'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'JPush'

end
